mvn install:install-file -Dfile=./resources/lib/xml.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.javax.xml -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/xml-apis.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.javax.xml-apis -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/xmlParserAPIs.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.javax.parsers -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/xmlparserv2.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.javax.parsersv2 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/DDbE.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.com.ibm.DDbE -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/xerces.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.javax.xerces -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/AbcDatalog-0.5.0.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.edu.harvard.seas.pl.abcdatalog -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/pm-module/OpenXES/OpenXES.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.pm.org.deckfour.OpenXES -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=./resources/lib/pm-module/OpenXES/Spex.jar -DgroupId=at.jku.dke.etutor -DartifactId=legacy.pm.org.deckfour.Spex -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
