
	
	
DROP TABLE if exists error_categories cascade;
DROP TABLE if exists error_grading_group cascade;
DROP TABLE if exists error_gradings cascade;
DROP TABLE if exists facts cascade;
DROP TABLE if exists exercise cascade;
DROP TABLE if exists predicates cascade;
DROP TABLE if exists unchecked_terms cascade;


CREATE TABLE  error_categories (	
	NAME VARCHAR(25) NOT NULL, 
	ID NUMERIC PRIMARY KEY 
   ); 
  
  COPY error_categories
  FROM 'C:\Users\Public\datalog\ERROR_CATEGORIES_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;


  CREATE TABLE error_grading_group
   (	
	 ID NUMERIC PRIMARY KEY
   );

  COPY error_grading_group
  FROM 'C:\Users\Public\datalog\ERROR_GRADING_GROUP_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;
  
  
  CREATE TABLE error_gradings
   (
	GRADING_GROUP NUMERIC NOT NULL, 
	GRADING_LEVEL NUMERIC NOT NULL, 
	GRADING_CATEGORY NUMERIC NOT NULL, 
	MINUS_POINTS NUMERIC(4,1) NOT NULL, 
	 CONSTRAINT GRADING_GRAD_UNIQUE UNIQUE (GRADING_GROUP, GRADING_CATEGORY),
	 CONSTRAINT GRADING_CAT_ID FOREIGN KEY (GRADING_CATEGORY)
	  REFERENCES ERROR_CATEGORIES (ID), 
	 CONSTRAINT GRADING_ID FOREIGN KEY (GRADING_GROUP)
	  REFERENCES ERROR_GRADING_GROUP (ID) ON DELETE CASCADE
   );
   
     COPY error_gradings
  FROM 'C:\Users\Public\datalog\ERROR_GRADINGS_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;
   
  CREATE TABLE FACTS
   (
	   FACTS VARCHAR(4000 ) NOT NULL , 
	ID NUMERIC PRIMARY KEY, 
	NAME VARCHAR(20) NOT NULL
   );
  
       COPY FACTS
  FROM 'C:\Users\Public\datalog\FACTS_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;
   
   
     CREATE TABLE exercise
   (	   
	ID NUMERIC PRIMARY KEY, 
	QUERY VARCHAR(1500) NOT NULL, 
	FACTS NUMERIC NOT NULL, 
	GRADINGS NUMERIC, 
	POINTS NUMERIC(4,1), 
	 CONSTRAINT EXERCISE_FACT_ID FOREIGN KEY (FACTS)
	  REFERENCES FACTS (ID), 
	 CONSTRAINT EXERCISE_GRAD_ID FOREIGN KEY (GRADINGS)
	  REFERENCES ERROR_GRADING_GROUP (ID)
   );
   
       COPY exercise
  FROM 'C:\Users\Public\datalog\EXERCISE_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;
   
  CREATE TABLE predicates
   (
	NAME VARCHAR(35) NOT NULL, 
	EXERCISE NUMERIC(10,0) NOT NULL, 
	 CONSTRAINT PREDICATES_FK_EXERCISE FOREIGN KEY (EXERCISE)
	  REFERENCES EXERCISE (ID) ON DELETE CASCADE 
   );

    COPY predicates
  FROM 'C:\Users\Public\datalog\PREDICATES_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;
   

  CREATE TABLE UNCHECKED_TERMS
   (	
	 PREDICATE VARCHAR(35) NOT NULL, 
	TERM VARCHAR(35) NOT NULL, 
	POSITION NUMERIC(10,0) NOT NULL, 
	EXERCISE NUMERIC(10,0) NOT NULL, 
	 CONSTRAINT UNCHECKED_EXERCISE_ID FOREIGN KEY (EXERCISE)
	  REFERENCES EXERCISE (ID)
   );
 
    COPY unchecked_terms
  FROM 'C:\Users\Public\datalog\UNCHECKED_TERMS_DATA_TABLE.csv'
  DELIMITER ',' 
  CSV 
  HEADER;
   


