package at.jku.dke.etutor.modules.ra2sql;// $ANTLR 2.7.2: "parser_grammar.g" -> "RAParser.java"$


			
public interface RAParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_LEFTPARENTHESES = 4;
	int LITERAL_RIGHTPARENTHESES = 5;
	int LITERAL_SELECTION = 6;
	int LITERAL_LEFTBRACKET = 7;
	int LITERAL_COMMA = 8;
	int LITERAL_RIGHTBRACKET = 9;
	int LITERAL_PROJECTION = 10;
	int LITERAL_RENAMING = 11;
	int LITERAL_LEFTARROW = 12;
	int LITERAL_JOIN = 13;
	int LITERAL_INTERSECTION = 14;
	int LITERAL_UNION = 15;
	int LITERAL_OUTER_JOIN = 16;
	int LITERAL_DIVISION = 17;
	int LITERAL_MINUS = 18;
	int LITERAL_CARTESIANPRODUCT = 19;
	int LITERAL_LEFTSEMI = 20;
	int LITERAL_RIGHTSEMI = 21;
	int LITERAL_LEFTCURLY = 22;
	int LITERAL_RIGHTCURLY = 23;
	int LITERAL_LESSTHAN = 24;
	int LITERAL_EQUAL = 25;
	int LITERAL_GREATERTHAN = 26;
	int LITERAL_APOSTROPHE = 27;
	int STRING = 28;
	int NUMBER = 29;
	int LITERAL_DOT = 30;
	int WS = 31;
}
