create sequence closure_id_seq1;

alter sequence closure_id_seq1 owner to etutor;

create sequence exercise_id_seq;

alter sequence exercise_id_seq owner to etutor;

create table assignment
(
    id          bigint generated by default as identity
        primary key,
    relation_id bigint,
    is_exam     boolean,
    is_solved   boolean,
    student_id  bigint,
    type        varchar(255)
);

alter table assignment
    owner to etutor;

create table relation
(
    id          bigint generated by default as identity
        constraint exercise_pkey
            primary key,
    attributes  text[],
    normal_form text not null
);

alter table relation
    owner to etutor;

alter sequence exercise_id_seq owned by relation.id;

create table closure
(
    id          bigint generated by default as identity
        primary key,
    left_side   text[],
    right_side  text[],
    relation_id bigint
        constraint fkk9a11ck0qpmrksvq8ewkwnesd
            references relation
);

alter table closure
    owner to etutor;

create table dependency
(
    id          bigint generated by default as identity
        primary key,
    left_side   text[],
    right_side  text[],
    relation_id bigint
        constraint fkf7ckjur0r23nsk5mge7jabifj
            references relation,
    violates    text
);

alter table dependency
    owner to etutor;

create table key
(
    id          bigint generated by default as identity
        primary key,
    left_side   text[],
    right_side  text[],
    relation_id bigint
        constraint fkki8mpegbplkj8rpr7sqqwsiva
            references relation
);

alter table key
    owner to etutor;

create table minimal_cover
(
    id            bigint generated by default as identity
        primary key,
    left_side     text[],
    reasons       text[],
    right_side    text[],
    relation_id   bigint
        constraint fkb6g74n8sbdatip1r9p3wmby5q
            references relation,
    dependency_id bigint
        constraint fk2j7mr69wmw0fji866npjnrgaj
            references dependency
);

alter table minimal_cover
    owner to etutor;

create table solution
(
    id                  bigint generated by default as identity
        primary key,
    closure_combination varchar(255),
    closure_results     varchar(255)
);

alter table solution
    owner to etutor;

