create sequence closure_id_seq1;

alter sequence closure_id_seq1 owner to etutor;

create sequence assignment_id_seq;

alter sequence assignment_id_seq owner to etutor;

create sequence dependency_id_seq;

alter sequence dependency_id_seq owner to etutor;

create sequence exercise_id_seq;

alter sequence exercise_id_seq owner to etutor;

create table relation
(
    id          bigint generated by default as identity
        constraint exercise_pkey
            primary key,
    attributes  text[],
    normal_form text not null
);

alter table relation
    owner to etutor;

alter sequence exercise_id_seq owned by relation.id;

create table task
(
    id               bigint generated by default as identity
        constraint assignment_pkey
            primary key,
    relation_id      bigint
        constraint task_relation_id_fk
            references relation
            on update cascade on delete cascade,
    type             varchar(255),
    closure_group_id bigint,
    closure_id       bigint
);

alter table task
    owner to etutor;

alter sequence assignment_id_seq owned by task.id;

create table closure
(
    id          bigint generated by default as identity
        primary key,
    left_side   text[],
    right_side  text[],
    relation_id bigint
        constraint fkk9a11ck0qpmrksvq8ewkwnesd
            references relation
            on update cascade on delete cascade,
    closure_id  bigint
        constraint fkmeo557f4gdclygdl9kcxubais
            references task
);

alter table closure
    owner to etutor;

alter table task
    add constraint task_closure_id_fk
        foreign key (closure_id) references closure
            on update cascade on delete cascade;

create table functional_dependency
(
    id          bigint generated by default as identity
        constraint dependency_pkey
            primary key,
    left_side   text[],
    right_side  text[],
    relation_id bigint
        constraint fkf7ckjur0r23nsk5mge7jabifj
            references relation
            on update cascade on delete cascade,
    violates    text
);

alter table functional_dependency
    owner to etutor;

alter sequence dependency_id_seq owned by functional_dependency.id;

create table key
(
    id          bigint generated by default as identity
        primary key,
    left_side   text[],
    right_side  text[],
    relation_id bigint
        constraint fkki8mpegbplkj8rpr7sqqwsiva
            references relation
            on update cascade on delete cascade
);

alter table key
    owner to etutor;

create table minimal_cover
(
    id            bigint generated by default as identity
        primary key,
    left_side     text[],
    reasons       text[],
    right_side    text[],
    relation_id   bigint
        constraint fkb6g74n8sbdatip1r9p3wmby5q
            references relation
            on update cascade on delete cascade,
    dependency_id bigint
        constraint fk2j7mr69wmw0fji866npjnrgaj
            references functional_dependency
            on update cascade on delete cascade
);

alter table minimal_cover
    owner to etutor;

