name: ci

on:
  push:
    branches:
      - "main"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: kevschuetz
  PASSWORD: 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
  OBJECTS_VERSION: 1.1

jobs:
  build-objects-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout etutor-objects
      uses: actions/checkout@v2
      with:
        repository: eTutor-plus-plus/objects
        ref: main
        path: objects
    - name: Build objects with Maven
      run: mvn clean install -f objects
    - name: Upload other repository artifact
      uses: actions/upload-artifact@v2
      with:
        name: objects
        path: objects/target/*.ja

    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn -B package -DskipTests -Detutor.objects.path=../objects/target/etutor-objects-1.1.jar --file pom.xml

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  
